config/routes.rb
Rails.application.routes.draw do

  devise_scope :usuario do
    get 'sign_out' => 'devise/sessions#destroy'
    get 'salir' => 'devise/sessions#destroy',
      as: :terminar_sesion
    post 'usuarios/iniciar_sesion', to: 'devise/sessions#create'
    get 'usuarios/iniciar_sesion', to: 'devise/sessions#new',
      as: :iniciar_sesion

    # El siguiente para superar mala generación del action en el formulario
    # cuando se monta en sitio diferente a / y se autentica mal (genera 
    # /puntomontaje/puntomontaje/usuarios/sign_in )
    if (Rails.configuration.relative_url_root != '/') 
      ruta = File.join(Rails.configuration.relative_url_root, 
                       'usuarios/sign_in')
      post ruta, to: 'devise/sessions#create'
      get  ruta, to: 'devise/sessions#new'
    end
  end
  devise_for :usuarios, :skip => [:registrations], module: :devise
  as :usuario do
    get 'usuarios/edit' => 'devise/registrations#edit', 
      :as => 'editar_registro_usuario'    
    put 'usuarios/:id' => 'devise/registrations#update', 
      :as => 'registro_usuario'            
  end
  resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' } 

  root 'msip/hogar#index'

  namespace :admin do
    ab = ::Ability.new
    ab.tablasbasicas.each do |t|
      if (t[0] == '') 
        c = t[1].pluralize
        resources c.to_sym, 
          path_names: { new: 'nueva', edit: 'edita' }
      end
    end
  end

  mount Heb412Gen::Engine, at: "/", as: 'heb412_gen'
  mount Mr519Gen::Engine, at: "/", as: 'mr519_gen'
  mount Msip::Engine, at: "/", as: 'msip'
end

app/models/ability.rb
class Ability  < Heb412Gen::Ability


  # Autorizacion con CanCanCan
  def initialize(usuario = nil)
    initialize_mr519_gen(usuario)

    if usuario && usuario.rol
      can(:read, Heb412Gen::Doc)
      can(:read, Heb412Gen::Plantilladoc)
      can(:read, Heb412Gen::Plantillahcm)
      can(:read, Heb412Gen::Plantillahcr)

      case usuario.rol
      when Ability::ROLANALI
        can([:create, :update, :destroy, :edit] , Heb412Gen::Doc)

      when Ability::ROLADMIN, Ability::ROLDIR
        can(:manage, Heb412Gen::Doc)
        can(:manage, Heb412Gen::Plantilladoc)
        can(:manage, Heb412Gen::Plantillahcm)
        can(:manage, Heb412Gen::Plantillahcr)
        can(:manage, Heb412Gen::Carpetaexclusiva)
      end
    end
  end # initialize

end # class

app/models/usuario.rb
require 'mr519_gen/concerns/models/usuario'

class Usuario < ActiveRecord::Base
  include Mr519Gen::Concerns::Models::Usuario
end

app/controllers/application_controller.rb
class ApplicationController < Msip::ApplicationController

  protect_from_forgery with: :exception
  helper Msip::Engine.helpers

end

app/controllers/msip/personas_controller.rb
require 'msip/concerns/controllers/personas_controller'

class Msip::PersonasController < Heb412Gen::ModelosController

  include Msip::Concerns::Controllers::PersonasController
  include Msip::Engine.routes.url_helpers

  def vistas_manejadas
    ['Persona']
  end

  def index(c = nil)
    super(c)
  end

end

app/controllers/usuarios_controller.rb
require 'msip/concerns/controllers/usuarios_controller'

class UsuariosController < Heb412Gen::ModelosController

  include Msip::Concerns::Controllers::UsuariosController

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Heb412Gen::ApplicationHelper
end

app/views/layouts/application.html.erb
<% content_for :title do %>
    <%= Msip.titulo %>
<% end %>

<% content_for :marca do %>
    <%= Msip.titulo %>
<% end %>

<% content_for :menu do %>
  <%= grupo_menus do %>
    <% if !current_usuario.nil? %>
        <%= opcion_menu "Organizaciones sociales", msip.orgsociales_path %>
        <%= opcion_menu "Personas", msip.personas_path %>
    <% end %>
  <% end %>
  <%= grupo_menus :pull => :right do %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo "Documentos" do %>
        <%= opcion_menu "Nube", heb412_gen.sisini_path, 
          desplegable: true %>
        <% if can?(:update, Heb412Gen::Plantillahcm) %>
          <%= opcion_menu "Plantillas para listado", 
            heb412_gen.plantillashcm_path,
            desplegable: true %>
        <% end %>
        <% if can?(:update, Heb412Gen::Plantillahcr) %>
          <%= opcion_menu "Plantillas para registro", 
            heb412_gen.plantillashcr_path,
            desplegable: true %>
        <% end %>
      <% end %>
      <%= despliega_abajo "Administrar" do %>
        <%= opcion_menu "Clave y tema", main_app.editar_registro_usuario_path,
          desplegable: true %>
        <% if current_usuario.rol == Ability::ROLADMIN %>
          <%= opcion_menu "Usuarios", main_app.usuarios_path,
            desplegable: true %>
          <%= opcion_menu "Copia de respaldo cifrada", 
            msip.respaldo7z_path, desplegable: true %>
        <% end %>
        <% if can? :manage, Mr519Gen::Formulario %>
          <%= opcion_menu "Formularios", mr519_gen.formularios_path, 
            desplegable: true %>
        <% end %>
        <% if current_usuario.rol == Ability::ROLADMIN %>
          <%= opcion_menu "Tablas Básicas", msip.tablasbasicas_path,
            desplegable: true %>
        <% end %>
      <% end %>
      <%= opcion_menu "Salir #{current_usuario.nusuario}", 
        main_app.terminar_sesion_path %>
    <% else %>
      <%= opcion_menu "Acerca de", msip.acercade_path %>
      <%= opcion_menu "Iniciar Sesión", main_app.iniciar_sesion_path %> 
    <% end %>
  <% end %>
<% end %>

<% content_for :piedepagina do %>
  <p><span class='derechos'>Sistema de información de 
    <a href='https://github.com/pasosdeJesus/heb412'>código abierto</a> con 
    <a href="https://github.com/pasosdeJesus/msip/blob/main/LICENCIA.md">licencia ISC</a>
    <br/>
    Desarrollado por <a id='pasosdeJesus' href="http://www.pasosdeJesus.org" target="_blank">Pasos de Jesús</a>. 2023. 
  </span></p>
<% end %>

<%= render template: "layouts/msip/application" %>